### ISSUE TITLE
CLIZed tool : Must

### ISSUE THREAD

**Issue by RSoulatIOHK** [input-output-hk/ptt-cli#10]
A/C Main list:
- [ ] input-output-hk/plutus-testing-tool#32 
- [ ] input-output-hk/ptt-cli#3
- [ ] input-output-hk/ptt-cli#4
- [ ] input-output-hk/ptt-cli#5
- [ ] input-output-hk/ptt-cli#6
- [ ] input-output-hk/ptt-cli#7

A/C Secondary list Should: 
- [ ] input-output-hk/ptt-cli#8
- [ ] input-output-hk/ptt-cli#9

A/C Thirdary list Nice to have:
- [ ] input-output-hk/ptt-cli#2

![Image](https://github.com/user-attachments/assets/2084f6bd-8e85-4489-ab3f-c19705ea6e07)
